server:
  port: 8020
  
spring: 
  application:   #定义服务名称
    name: consumer-user
  
#eureka:
#  client:
#    register-with-eureka: false    #不会将自己的信息注册到eureka中
#    service-url:
#     #链接注册中心集群
#       defaultZone: http://localhost:7000/eureka
       
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: consumer-user-8020                #定义微服务的名称
    prefer-ip-address: true                        #是否显示IP和端口
    
feign:
  hystrix:
    enabled: true                 #启动熔断器机制